### PR TITLE
Minor punctuation optimization

### PR DESCRIPTION
**Pull request by nkh0472**
#### Changes proposed in this pull request:
- ~Add period for 3 sentences~
- Remove a period in line 77, for further info, see below:

https://github.com/jrsoftware/issrc/blob/50fa9edf6f093543793d36aef3daad04d9553523/ISHelp/isxfunc.xml#L304-L305

### CODE REVIEW

**Review by pzhlkj6612 — APPROVED** [review]

**Comment by kira-96** [comment]
原文中这里没有句号。

https://github.com/jrsoftware/issrc/blob/50fa9edf6f093543793d36aef3daad04d9553523/Files/Default.isl#L43-L44

https://github.com/jrsoftware/issrc/blob/50fa9edf6f093543793d36aef3daad04d9553523/Files/Default.isl#L78

**Comment by pzhlkj6612** [comment]
有个问题： `ErrorCreatingDir` (https://github.com/jrsoftware/issrc/blob/50fa9edf6f093543793d36aef3daad04d9553523/Files/Default.isl#L77C1-L77C17) 原文也没有句号，是否需要去掉译文中的句号？

**Comment by kira-96** [comment]
Inno Setup 翻译文件下载地址：https://jrsoftware.org/files/istrans/由于项目是托管在github上的，国内用户可能无法下载，如需简体中文翻译可通过以下地址下载。Inno Setup 简体中文翻译下载地址：https://github.com/kira-96/Inno-Setup-Chinese-Simplified-Translation/releases/latestInno Setup 5.x 的简体中文翻译下载地址：https://github.com/kira-96/Inno-Setup-Chinese-Simplified-Translation/tree/5.5.3+祝您生活美好，工作愉快！[此条邮件自动回复，如有误发请忽略，很抱歉给您带来不便。]

**Comment by nkh0472** [comment]
I don't think these missing periods were intentional. I just submitted a PR upstream to see if there are any comments.

**Pull request merged**
